services:
  - type: web
    name: assessment-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn assessment_web.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: assessment-db
          property: connectionString
  
  - type: pserv
    name: assessment-db
    env: postgresql
    plan: free
    ipAllowList: [] 