# Generated by Django 5.2.3 on 2025-07-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allow_retake',
            field=models.BooleanField(default=True, help_text='Allow candidates to retake this assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='show_results_immediately',
            field=models.BooleanField(default=True, help_text='Show results immediately after completion'),
        ),
    ]
