# Generated by Django 5.2.3 on 2025-07-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_allow_retake_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentType',
            new_name='Designation',
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
    ]
