# Generated by Django 5.2.3 on 2025-07-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_add_designations_and_categories'),
        ('assessments', '0003_rename_assessmenttype_designation_and_more'),
    ]

    operations = [
    ]
