# Generated by Django 5.2.3 on 2025-07-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_merge_20250701_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
